### ISSUE TITLE
Ice connection failed react native

### ISSUE THREAD

**Issue by TriPSs** [feross/simple-peer#445]
I'm trying to implement `webtorrent` lib in my react native application using `react-native-webrtc` but the `simple-peer` library keeps giving this error:
```
simple-peer [50766ba] iceStateChange (connection: failed) (gathering: gathering)
simple-peer [50766ba] destroy (error: Ice connection failed.)
webtorrent:peer destroy 2d5744303032302d756b692b6a4c7a7671464155 (error: Ice connection failed.)
```
Does anyone now how i can tackle this issue?

**Comment by t-mullen** [comment]
Have you tried the troubleshooting steps in #202?

**Comment by TriPSs** [comment]
I tried to do them but did not know what to do in some cases as the integration of simple-peer is in other libs.

**Comment by t-mullen** [comment]
I don't think webtorrent uses the latest simple-peer, so it's difficult to tell if your issue has already been solved in this library.

**Comment by TriPSs** [comment]
I forced my app to use the `simple-peer` from GIT but it's still happening.

**Comment by t-mullen** [comment]
I'll see what I can do about getting our tests running on react-native and see if you issue comes up. We don't officially support it right now since it's WebRTC implementation is outdated.

**Comment by feross** [comment]
> Webtorrent does not use the latest simple-peer, so it's difficult to tell if your issue has already been solved in this library.

This is fixed now :)

**Comment by TheSalarKhan** [comment]
Until react-native-webrtc adds support for 'addTrack' I've created a fork of simple-peer that works with react-native-webrtc.

Link: https://github.com/ExpandoPakistan/simple-peer-legacy

Leaving it here for anyone that needs react-native support in the meanwhile.
