### ISSUE TITLE
Safari users cannot hear remote audio, even though audio track is present 

### ISSUE THREAD

**Issue by feross** [feross/simple-peer#672]
In Safari iOS, the audio for remote streams doesn't work sometimes. The audio track is being sent in the SDP but there's no audio when I add the stream to a <video> tag. This happens 20% of the time and it's very perplexing.

What's super weird is that if I connect the iPhone to debug the Safari tab, and I select the remote video element, and then I run $0.pause(); $0.play() the audio suddenly starts working. Somehow the audio track is present but the video tag is glitching and not playing it, it seems.

I wait for both 'track' events (one for video, one for audio) then I set `video.srcObject = stream`. Very basic WebRTC usage.

I can reproduce this after about 5 tries between iOS on the one side and desktop Safari/Chrome on the other.

This may be a bug in Safari's WebRTC or audio stack so I reported it here: https://bugs.webkit.org/show_bug.cgi?id=212669 just in case.

Anyone else seen this or have ideas?

**Comment by feross** [comment]
This is definitely a Safari bug: https://bugs.webkit.org/show_bug.cgi?id=198545

Closing since there's nothing `simple-peer` can do about it. Safari's WebRTC implementation needs a lot of work.

**Comment by feross** [comment]
Other related issues:

https://github.com/twilio/twilio-video.js/issues/922
https://github.com/twilio/twilio-video.js/issues/941

**Comment by anna-vasilko** [comment]
@feross Safari team from Apple communicated that the issue is fixed in the latest iOS beta 13.5.5, which is available for testing with the iOS dev account.
Our internal testing confirmed the fix. Any chance you could verify on your end?

**Comment by Dalton-Klein** [comment]
I am still not able to get iphones to play any sound in voice chats. PC users can hear them, the peers are established fine, but iphone users cannot hear anything.
